### ISSUE TITLE
[Bug]: `Address` comparison is incorrect

### ISSUE THREAD

**Issue by jarkkojs** [enarx/primordial#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

Both `T` and `U` are used for comparison, given that `#derive[]` is used for implementations. This is incorrect, as for memory address comparisons only location matter, not the contents. 

### Expected Behaviour

Order is based only to `T`.

### Environment Information

-

### Steps To Reproduce

-

**Comment by npmccallum** [comment]
Resolved in https://github.com/enarx/primordial/commit/805f59e344f0f2ed0e1534cc3a588ef3988f5b8c

**Comment by jarkkojs** [comment]
OK good.
